name: Синхронизация конфигурации

on: workflow_dispatch

env:
  YARD_RELEASES_USER: ${{ secrets.YARD_RELEASES_USER }}
  YARD_RELEASES_PWD:  ${{ secrets.YARD_RELEASES_PWD }}

jobs:
  build:
    runs-on: self-hosted

    steps:

      - name: Актуализация git
        uses: actions/checkout@v2.4.0

      - name: Подготовка окружения
        shell: cmd
        run: |
          chcp 65001
          mkdir distr
          copy description.json distr
          cd distr
          mkdir SSL31
          copy description.json SSL31

      - name: Синхронизация с помощью yard
        shell: cmd
        run: |
          chcp 65001
          yard process --work-dir ./ ./yardsettings.json

      - name: Отправка изменений в github репо
        uses: ad-m/github-push-action@master # fixme
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: ${{ github.ref }}